<?php

/**
 * Script with view-parameters that is used for testing.
 *
 * @category PHP
 * @package Mol_Mail
 * @subpackage Tests
 * @author Matthias Molitor <matthias@matthimatiker.de>
 * @copyright 2012 Matthias Molitor
 * @license http://www.opensource.org/licenses/BSD-3-Clause BSD License
 * @link https://github.com/Matthimatiker/MolComponents
 * @since 04.07.2012
 */

$param = isset($this->param) ? $this->param : null;

?>
<?= $param; ?>